import 'dart:math';
import 'package:random_string/random_string.dart';

class KeyStore {
  var random = new Random();

  KeyItem genarateKeyitem() {
    int code = random.nextInt(82);
    return KeyItem(keycode: _keycodelist[code], key: _keylist[code]);
  }

  String findkey(String keycode) {
    int index = _keycodelist.indexWhere((note) => note.startsWith(keycode));
    print(index);

    return _keylist[index];
  }

  final List<String> _keycodelist = [
    'a',
    'b',
    'c',
    'd',
    'e',
    'f',
    'g',
    'h',
    'i',
    'j',
    'k',
    'l',
    'm',
    'n',
    'o',
    'p',
    'q',
    'r',
    's',
    't',
    'u',
    'v',
    'w',
    'x',
    'y',
    'z',
    'A',
    'B',
    'C',
    'D',
    'E',
    'F',
    'G',
    'H',
    'I',
    'J',
    'K',
    'L',
    'M',
    'N',
    'O',
    'P',
    'Q',
    'R',
    'S',
    'T',
    'U',
    'V',
    'W',
    'X',
    'Y',
    'Z',
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '-',
    '=',
    '!',
    '@',
    '#',
    '%',
    '^',
    '&',
    '*',
    '(',
    ')',
    '_',
    '+',
    ',',
    '.',
    '/',
    '<',
    '>',
    '?',
    ';',
    ':',
    '"',
    '[',
    ']',
    '|'
  ];

  List<String> _keylist = [
    '0yxpFFscMMaBPbmWAiWImVd8LdfQmDjg',
    'HgLeG9JSRVhA76JVzlWiATgrOVqaMCch',
    'mvdXHc8Iw67H4Hxi0sznIucFaLm51kPL',
    'z9vFXFGBgxGvR74dQ4trNe35ox3PwYBv',
    'O6Oiy8lKtPOoZLxihGQPoKezHi5w7Bcp',
    'YuzSaz6Ktxl4kt6pxRp2i9heQxf39ydC',
    'Y6I6GaM3VvUwLMIwp926966uLZRqNHLe',
    'Lrf5PIDE3s2eSLjRcj0GSgUXbJi35mMo',
    'cZjt2T6zb4LTkgJqQlcDixqDnZoRJ04D',
    'vVouCni6WC6HfoJIIGm7Y0ZAAqA4hxnu',
    'DjEu6JTXbF8jOH7x0qtwQiq9ii6Ms0GY',
    'lqCtt7A0Wh7I7YQZmVuI5HwIdct52N66',
    'DDEcVM6sKxGToyDa9uKu5NjG8DFpm8iG',
    'WVIFZDZOuQCRj0eVQ8qdallIqfwIHYVe',
    'MWc8Be8taYReC6DZyQSkLOM9pTb7bDX5',
    'UqgMMjy44SxLZubxMmGDYcaGOE3aYjz2',
    '5YSOLkyPHKTn92yQWaK1KbY62giLqBHq',
    'sCtnQpffQpubrWpFUhiZrNWHMNaKCCOa',
    'tOCLaSG7KqmSRj7EBGjXvsV7540Q9Wma',
    'WOz8xY1l6388wkAijmTZKyAgnxw1oNKb',
    'y87uI5o22xvRYPogfmFE7DQ411hNcRu1',
    'NJUGp4JOpjVjGZKIM8KPsbaDD5wciHN8',
    'sFdptN4NpdUqYc42ABZJsPKYzRJf5Pdo',
    'nfx6fW6u4MoJXAl6IiT6DrdZjrw991Mm',
    'sYk5Ps7oNReBWqFirTolVBKCPPdtNwXu',
    'L7LmhMYblrOJhZYK0bJfhnYigtCltJpP',
    'jY2hOxOGGxJ9aHqpdBRkls747vmskIB0',
    '4GAdEPIV9BL3IL8VtNJSnRfKJyMpEdyt',
    '0mRUzlpkgnPhrzzzhpCyv2X2bUWxNkDD',
    'Ar3lhzprM2c3lgzEuwFTjrsKDdLEE8wf',
    'bXrrnhjYS3ZURhksJMoyteohCXLnKtAf',
    'YgGQZ9n2lyY4ZYV5nUJ7FCWLzr1l7wKx',
    'UDGOfscmtHh9siJ1P7Ykiz6gs78vOrSF',
    'J2aL2vf2dmoI2ZaqsWX7VxioQx6oAETE',
    'n0O071YoeIzuyYHCCqCGBzBJM9W2avDG',
    'opHDro2upbZyvf97KEshycr8wdoUlPoB',
    'x7m9UvOvhhEcp0p4N8dS19KHlF9w5AE6',
    'xWbiXLjdH5StPlou1Ru0jJIoCs2PYqog',
    'awzhq1ozBZJjQfi6DYHeHQclVEH1oYzZ',
    's2bWI40PkQHCAH60wHggXR9U9aOX7ZBv',
    'Klj8Yf1xKL3IONWoVi2FYpdzUUxBPr5O',
    'lus76XuTF5Yj1CKlIPaXk0EyWR0DlE38',
    'jMKJQUsxXAQih4SRukHJPR4aNRQyYjdY',
    'bSFnwoyRaIKIP5JSqFKio2Dup30ZftBg',
    'wNEQLBE4n58RPmq9tM0xzxdNB32eoQWN',
    'r2M7u5VaZ0rCvG9OWjwICC2KINnPBFml',
    'Z7m5lyDbXJhk1j28g2zYmzrk6blITfNr',
    '8ddCjWbqIYWfhIBBOr8SckcLAyxgvGrR',
    'rip1Kw5Nqy7I7QXoAOuqzM6qSzLJ4lKO',
    '2xxBaThi0uPrKGtEgJ4fmJxwA9Vuyfo1',
    '12OKO1v68RodbDrBmdgZXiOLpWZWYXB0',
    'J5XUBCmsslqYBgOkrHi3xvpeykpT8UiH',
    'DNe4IPNcOj66QaiyZK8ajoSw3vKYPFLt',
    'yTfIBCgYgcmYgsRKUrihMEikkmrx0OTZ',
    'qq71AHaOZOrV4iDkAx08LeB40LdlBmhQ',
    'KAWgQHyqbW7PUG2ZS79YxDVXtFZmjBCe',
    'HJeW3nZK1MptukSeQLtAPH2Wbhp9VJTi',
    'VW3cYqTMIRyX15JYk9iY8IZtBi4l1PfL',
    'vBiaGhZu6rG8l1gGpGuYo00W0LSf3dlP',
    'RqPLTCaHMRCIsjA9uasfo3ZWgoQZnVWc',
    'BOtT6dz9qa5vKmppRxhDttdJI3Vsn0pt',
    'zT3y4bfdtVMoRTV4YtEsCxejJJSlGSQ2',
    '8EVNpMpIUgl049S5c143pClAe34gGyaN',
    'k66VxT2fUKAci1SDhHb2Tbuw2arcZibn',
    'b1OenJO3ej0vlPKbliqP8XLxAaY7QlJK',
    'Lrow5qfD30MSuZOQDAL6rkQ1dSDH2Vq3',
    'fM2q3LtXgmTesedOEznRU3EoTs61icId',
    '7Dy6kYQGxRyGsDtWFJWc5P1lAf18eKmz',
    'JjOFgalvuAZtEaIHxpOg96cfvfLQ6dZi',
    'sDLqgsesOaDUHnyTSgwlUWiEBSqLaCu8',
    'P1LcN1UXHhuRuzqEzsO6oTU18C8RcgsS',
    'SkoNcabWroNV5l6KIkBMfpzXqJbz2OTG',
    'jUgGuuYEDYIYqXfap9zlb2xQ0uFKTfLZ',
    'nOdzxHEbRNiqFfKM6fUAMLF2WOwiT9Mn',
    '2c7WPieR7ptpkGDDyVfSbrYsFDkNpKGd',
    'Jqer6VqA09wMKCjIHozwdpcDTw10N4RU',
    'DzUo0JZYyENVIOspYXl0xfiI4oAiZ4ai',
    'VNQH8jAgiUYTqHME2h89Ty427ky7SGJp',
    'TvRkAtuZEJVAK6RWRtJsGWy70viiH83E',
    'cn5UmWxWRp41En1WeMAXB4qcy5go8Fdx',
    'pfQ5iBHcLLFIoxkDZAS7XrUoiDWdgYbb',
    'HZwA1hf195r1AiI1TtajIfglZ6gcCs8e',
    'FoM7oHNEURFlJQz2LluBXQqC4bgWZ1l0',
    'wD4ko05JbSUL643o192PJieZpQcqyifr',
    'Xr9K7p6iVBL2yeiy5Cuj3dnXWAymep5a',
    'zB0Y7MvoYWWgSHimfiBn3RuIUAo1rNLn',
    'LhK9U5cnmkCV54NgyO9eid0osxjwMahl',
    'Vbd2JFSvri9t61sFYtFmUPuZjQq4dJua',
    'O7smUNnuH5QAcXHcG6e6CE2axxBSB1dc',
    'VlEe52iPJp50PjnY0xDy1sDGvXkjcVHK',
    '955vnclo1lP4cdjCN4MRgB9BfFuDMRWh',
    'Bhk0dLZSpmT6UwVd8M3Y59EsJY1qk2uz',
    'k8WgQGC84cN5tbCeb30QWAg3mvAipUm9',
    'pQPg8Qo3CIhxeQKWHY9Z3YyWxkGwniJi',
    'HdyPwI3FwaWEW99TEp2tmTvIWqxqxGw5',
    'hWB93ZoYrUY8bPf4xGsQTlIaKLbqFZkh',
    'fiBm9EmYZWKySIIE3YDcZPBv96Pq2DgP',
    'w5raybSzy9iyHk827W41JVTYtDhXFdGW',
    '3ZoCyMInoWHgW0EP7QO2Uw1jyMbitiMb',
    '0uNRMUIDTJhOnOXoalAYGlgrxVPYCaKF',
    '65XVoNdnFFDKuWaUUO9ZYL2unPB5vQ4G',
    'iKqOWSVl1fIDAwY4pz3A14urztQ7292J',
    'vDVteumjjKITqkNMi37Hjdcs7Nl7SJQw',
    'aP9AyjUbYtwNRNNVA0CUWoTKqoj4gjks',
    'MJagIQbNpGvcFEj7SBgJXDf68Tr8aDOR',
    '5biM3RWYIqTdKY8nzIu4mtSa4jWp3Kbh',
    'mbnfjaFuBZwL6FPL6TPInGIuQ9x2AI5g',
    'sVsftatGTrOHdrAnPsQQ71ftpoRgSYcp',
    'kaAxx6iG5TEhLOqh1sYt0MpXG0DSdDBI'
  ];

  static String genaratekeycode() {
    String keycode = randomAlphaNumeric(32);
    return keycode;
  }
}

class KeyItem {
  final String keycode;
  final String key;

  KeyItem({required this.keycode, required this.key});
}
